;;; git-overleaf-autoloads.el --- automatically extracted autoloads (do not edit)   -*- lexical-binding: t -*-
;; Generated by the `loaddefs-generate' function.

;; This file is part of GNU Emacs.

;;; Code:

(add-to-list 'load-path (or (and load-file-name (directory-file-name (file-name-directory load-file-name))) (car load-path)))



;;; Generated autoloads from git-overleaf-auth.el

(autoload 'git-overleaf-authenticate "git-overleaf-auth"
  "Obtain cookies for URL using `git-overleaf-auth-backend'.
If URL is nil, use `git-overleaf-url'.

(fn &optional URL)" t)
(register-definition-prefixes "git-overleaf-auth" '("git-overleaf--"))


;;; Generated autoloads from git-overleaf.el

(autoload 'git-overleaf-clone "git-overleaf"
  "Clone a full Overleaf project into TARGET-DIRECTORY.
If URL is nil, use `git-overleaf-url'.

(fn &optional URL TARGET-DIRECTORY)" t)
(autoload 'git-overleaf-init "git-overleaf"
  "Bind the Git repo in DIRECTORY to a remote Overleaf project on URL.
The command stores project metadata and initializes the hidden base
snapshot used by later `git-overleaf-push' and
`git-overleaf-pull' runs, but does not automatically pull or push.

(fn &optional DIRECTORY URL)" t)
(autoload 'git-overleaf-push "git-overleaf"
  "Push the current Git repo to its configured Overleaf project.
Staged changes are committed automatically before the remote snapshot is
fetched.  When unstaged changes exist, prompt whether to stage them
first.

If a pending pull exists (merge conflict from a previous pull), verifies
the merge is complete and uploads the merged result.  If the remote has
diverged and no pending pull exists, signals an error asking you to run
`git-overleaf-pull' first.

When NOERROR is non-nil, silently return nil if DIRECTORY is not a
managed Overleaf repo, and demote push errors to warnings.  This is
useful for hooks such as `git-commit-post-finish-hook'.

(fn &optional DIRECTORY NOERROR)" t)
(autoload 'git-overleaf-overwrite-remote "git-overleaf"
  "Overwrite the configured Overleaf project with the current Git repo.
Like `git-overleaf-push', staged changes are committed automatically
before upload.  Unlike `git-overleaf-push', remote Overleaf changes
are replaced by the local `HEAD' snapshot.

(fn &optional DIRECTORY)" t)
(define-obsolete-function-alias 'git-overleaf-push-force 'git-overleaf-overwrite-remote "2.0.0")
(autoload 'git-overleaf-pull "git-overleaf"
  "Pull the latest Overleaf snapshot into the current Git repo.
The working tree must be clean before pulling.

When the local branch has diverged from the remote, performs a
`git merge --no-ff --no-edit' directly on the current branch.  If the
merge succeeds, records the downloaded remote snapshot as the base so a
later `git-overleaf-push' uploads the merged result.  If there are
conflicts, records a pending-pull state and prompts you to resolve them,
commit, then run `git-overleaf-push' to complete the sync.

(fn &optional DIRECTORY)" t)
(autoload 'git-overleaf-browse-remote "git-overleaf"
  "Open the configured Overleaf project in a browser.

(fn &optional DIRECTORY)" t)
(autoload 'git-overleaf-force-stop "git-overleaf"
  "Stop all running background Overleaf operations.

This cancels tracked Emacs threads, interrupts external processes they
started, clears async operation locks, and discards pending foreground
callbacks.  The cancellation is best effort: external tools that have
already changed local or remote state are not rolled back." t)
(defvar-keymap git-overleaf-command-map "a" #'git-overleaf-authenticate "b" #'git-overleaf-browse-remote "c" #'git-overleaf-clone "k" #'git-overleaf-force-stop "l" #'git-overleaf-pull "p" #'git-overleaf-push "s" #'git-overleaf-push)
(register-definition-prefixes "git-overleaf" '("git-overleaf--"))


;;; Generated autoloads from git-overleaf-core.el

(autoload 'git-overleaf-read-cookies-from-file "git-overleaf-core"
  "Return a cookie loader function reading cookies from FILE.
To be used with `git-overleaf-cookies'.

(fn FILE)")
(autoload 'git-overleaf-save-cookies-to-file "git-overleaf-core"
  "Return a cookie saver function writing cookies to FILE.
To be used with `git-overleaf-save-cookies'.

(fn FILE)")
(register-definition-prefixes "git-overleaf-core" '("git-overleaf-"))


;;; Generated autoloads from git-overleaf-http.el

(register-definition-prefixes "git-overleaf-http" '("git-overleaf-"))


;;; Generated autoloads from git-overleaf-log.el

(autoload 'git-overleaf-log "git-overleaf-log" "\
Display the global Overleaf project log buffer." t)
(autoload 'git-overleaf-log-clear "git-overleaf-log" "\
Clear the global Overleaf project log buffer." t)
(register-definition-prefixes "git-overleaf-log" '("git-overleaf-"))


;;; Generated autoloads from git-overleaf-magit.el

(autoload 'git-overleaf-magit-setup "git-overleaf-magit"
  "Enable the Overleaf section in `magit-status' buffers.")
(register-definition-prefixes "git-overleaf-magit" '("git-overleaf-magit-"))


;;; Generated autoloads from git-overleaf-sync.el

(register-definition-prefixes "git-overleaf-sync" '("git-overleaf--"))


;;; Generated autoloads from git-overleaf-firefox.el

(autoload 'git-overleaf-firefox-cookies "git-overleaf-firefox"
  "Return Overleaf cookies imported from an existing Firefox profile.
If URL is nil, use `git-overleaf-url'.  The Firefox profile must
already contain a valid Overleaf login session.

(fn &optional URL)")
(register-definition-prefixes "git-overleaf-firefox" '("git-overleaf-firefox-"))

;;; End of scraped data

(provide 'git-overleaf-autoloads)

;; Local Variables:
;; version-control: never
;; no-byte-compile: t
;; no-update-autoloads: t
;; no-native-compile: t
;; coding: utf-8-emacs-unix
;; End:

;;; git-overleaf-autoloads.el ends here
